<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpswww.psegameshop.commy-accountalg_wc__7fdaf2</name>
   <tag></tag>
   <elementGuidId>e6cb2689-bf50-4f2f-9329-384caee036cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='m_-4857717272421212199body_content_inner']/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#m_-4857717272421212199body_content_inner > p > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8b3bf5fd-c8d7-4be5-a15b-5bbb63ad0a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.psegameshop.com/my-account/?alg_wc_ev_verify_email=eyJpZCI6NTQ5NzUsImNvZGUiOiI4NmYwM2NlZjc4ZmRkMzgwMWVlMGVhMGRhZTJiZmU3YyJ9</value>
      <webElementGuid>2329114a-be79-4abc-974a-884b5eb6f608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>c10ba8a2-820e-4f79-849a-ee12468e64e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://www.psegameshop.com/my-account/?alg_wc_ev_verify_email%3DeyJpZCI6NTQ5NzUsImNvZGUiOiI4NmYwM2NlZjc4ZmRkMzgwMWVlMGVhMGRhZTJiZmU3YyJ9&amp;source=gmail&amp;ust=1671470665664000&amp;usg=AOvVaw3EK2yV_UnKOI-B0cjd_nxO</value>
      <webElementGuid>72affb9c-7a3f-497f-85a2-4ff8f698ce5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://www.psegameshop.com/my-account/?alg_wc_ev_verify_email=eyJpZCI6NTQ5NzUsImNvZGUiOiI4NmYwM2NlZjc4ZmRkMzgwMWVlMGVhMGRhZTJiZmU3YyJ9</value>
      <webElementGuid>0e6da681-31a2-4b6d-a66e-2486b7fbf92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m_-4857717272421212199body_content_inner&quot;)/p[1]/a[1]</value>
      <webElementGuid>2093e2a8-5e8e-4b28-93ea-78e58428a4cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='m_-4857717272421212199body_content_inner']/p/a</value>
      <webElementGuid>e7de6fc6-c681-4cf7-a04b-a3c0f99bea4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activate Your Account'])[1]/following::a[1]</value>
      <webElementGuid>2cbb2bc9-ea77-4775-8f39-421f30ac74d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nonaktifkan untuk: Inggris'])[1]/following::a[2]</value>
      <webElementGuid>023806b3-7d49-4cfd-9ee5-647ffb658119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powered by Milenia Inovasi Solusindo'])[1]/preceding::a[4]</value>
      <webElementGuid>cbd9dec8-666f-4f9d-accc-a4fc1cf1312b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balas'])[1]/preceding::a[4]</value>
      <webElementGuid>6808f500-e08b-4cec-b39d-6a6daa7f28da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://www.psegameshop.com/']/parent::*</value>
      <webElementGuid>f39f08d8-5102-4b45-97dd-b83662781912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.psegameshop.com/my-account/?alg_wc_ev_verify_email=eyJpZCI6NTQ5NzUsImNvZGUiOiI4NmYwM2NlZjc4ZmRkMzgwMWVlMGVhMGRhZTJiZmU3YyJ9')]</value>
      <webElementGuid>920afc84-eb56-4200-8cfb-0b61d4ca97d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/p/a</value>
      <webElementGuid>6631ceb3-92a7-4db5-859a-e008ff48f3a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.psegameshop.com/my-account/?alg_wc_ev_verify_email=eyJpZCI6NTQ5NzUsImNvZGUiOiI4NmYwM2NlZjc4ZmRkMzgwMWVlMGVhMGRhZTJiZmU3YyJ9' and (text() = 'https://www.psegameshop.com/my-account/?alg_wc_ev_verify_email=eyJpZCI6NTQ5NzUsImNvZGUiOiI4NmYwM2NlZjc4ZmRkMzgwMWVlMGVhMGRhZTJiZmU3YyJ9' or . = 'https://www.psegameshop.com/my-account/?alg_wc_ev_verify_email=eyJpZCI6NTQ5NzUsImNvZGUiOiI4NmYwM2NlZjc4ZmRkMzgwMWVlMGVhMGRhZTJiZmU3YyJ9')]</value>
      <webElementGuid>7c5e57a2-438e-4de0-b68e-72d415844793</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
