<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Account</name>
   <tag></tag>
   <elementGuidId>415c1c7f-3713-4f73-a1ea-f40dd5e8f5d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='m_3812536323582726012body_content_inner']/p[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a35ceaa-33c6-4a27-9bde-43b4bdb93104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.psegameshop.com/my-account/</value>
      <webElementGuid>a73f7a2b-e4a2-4801-9045-6e2e6d0faa08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bgcolor</name>
      <type>Main</type>
      <value>#00a3ff</value>
      <webElementGuid>6d5f27be-72a1-4272-bb3b-bfd64b48c6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>79249971-4d8b-4d1e-b65a-204ef254782d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://www.psegameshop.com/my-account/&amp;source=gmail&amp;ust=1671470652327000&amp;usg=AOvVaw26q7fguRFer2vgTL_25JHi</value>
      <webElementGuid>98e1afad-bd82-4df4-b725-c79c259009cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Account</value>
      <webElementGuid>7ebc0e79-df89-407d-9b0d-63981f27f61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m_3812536323582726012body_content_inner&quot;)/p[3]/a[1]</value>
      <webElementGuid>ffbb70c1-a1c0-4a62-b823-c4bfb825370d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='m_3812536323582726012body_content_inner']/p[3]/a</value>
      <webElementGuid>f27ac8ea-8394-4b97-8d58-cdf405a3c9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Account')]</value>
      <webElementGuid>20d9b380-5d4e-428f-8fbb-c589a95717b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ads.sto13'])[1]/following::a[1]</value>
      <webElementGuid>f941a7cc-58e4-4c41-8fe0-3f37783b7fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to PS Enterprise Gameshop'])[1]/following::a[1]</value>
      <webElementGuid>73756a0b-a464-4f04-9bdc-d27ac06b4871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powered by Milenia Inovasi Solusindo'])[1]/preceding::a[4]</value>
      <webElementGuid>68ded773-cf62-4c14-9b87-6482763d759b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balas'])[1]/preceding::a[4]</value>
      <webElementGuid>f48fce6e-f2c1-4668-af16-68b0c94ecdb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Account']/parent::*</value>
      <webElementGuid>f4b0c135-f5b3-4516-a454-e24ccd8a61a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.psegameshop.com/my-account/')]</value>
      <webElementGuid>700e481b-3204-4c36-b31a-acf9c7e8c823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/a</value>
      <webElementGuid>6ffcf21f-eb1d-47f9-8737-0a6a8062213e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.psegameshop.com/my-account/' and (text() = 'View Account' or . = 'View Account')]</value>
      <webElementGuid>d341b966-9cc5-4819-a788-116c9da62c0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
