<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kotak Masuk5</name>
   <tag></tag>
   <elementGuidId>4306ec3f-0c90-460f-b938-43b9133d2aee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':57']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.aio.UKr6le</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9aee2dd0-ac4e-484e-8e2d-9f77563a7f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aio UKr6le</value>
      <webElementGuid>a4c214a8-1fc5-4983-918f-9b3859a0e11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kotak Masuk5</value>
      <webElementGuid>eb8575c5-16c0-4a41-b3a8-0445a3418446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:57&quot;)/div[@class=&quot;TN bzz aHS-bnt&quot;]/div[@class=&quot;aio UKr6le&quot;]</value>
      <webElementGuid>621e7397-5506-46d6-b5da-3fc79cc74cb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':57']/div/div[2]</value>
      <webElementGuid>6912553b-1cc9-46a2-9009-55ca5df5b912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[1]/following::div[9]</value>
      <webElementGuid>c57996a7-a4a5-4ba1-a5cc-0bcf5e8f17eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tulis'])[1]/following::div[18]</value>
      <webElementGuid>4d7753e0-51e2-463a-a169-1ba8dbe1e709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berbintang'])[1]/preceding::div[4]</value>
      <webElementGuid>2325c44c-013c-4b79-a434-56ae75571cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>f9541ebf-b89f-46d1-8cbe-185d9f261f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kotak Masuk5' or . = 'Kotak Masuk5')]</value>
      <webElementGuid>499a2851-ee5e-4254-95a4-b3eea04553f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
