<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Please activate your account</name>
   <tag></tag>
   <elementGuidId>cf4e2758-9046-44f9-bb09-8485b555977a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id=':ky']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>82031f3c-2279-45c6-b3e6-915620dd2779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bqe</value>
      <webElementGuid>c02acb2e-faed-4083-b057-adb774ea7b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thread-id</name>
      <type>Main</type>
      <value>#thread-f:1752573411415690590</value>
      <webElementGuid>a02af932-2a82-41ed-b393-ddf5aa7cf1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legacy-thread-id</name>
      <type>Main</type>
      <value>1852643b6e3a0d5e</value>
      <webElementGuid>33ac8232-e15f-4e03-80da-fe12926fa8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legacy-last-message-id</name>
      <type>Main</type>
      <value>1852643b6e3a0d5e</value>
      <webElementGuid>cb2c9163-387d-440a-a59f-e04b6ba13e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legacy-last-non-draft-message-id</name>
      <type>Main</type>
      <value>1852643b6e3a0d5e</value>
      <webElementGuid>067eaf73-8eed-42d3-b8cd-8bc92caa5229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please activate your account</value>
      <webElementGuid>a398e674-96ef-4e45-90ca-61b0d39c8634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:ky&quot;)/span[@class=&quot;bqe&quot;]</value>
      <webElementGuid>01b850cb-346a-4101-b03a-6fd738a20b1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id=':ky']/span</value>
      <webElementGuid>63b83725-a34b-4282-acba-6b7d5e85431e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PS Enterprise Games.'])[2]/following::span[2]</value>
      <webElementGuid>0443ccac-da57-43a8-9bdd-fa4671b23eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please activate your account'])[1]/following::span[5]</value>
      <webElementGuid>81e39888-9330-4382-9c45-057e43ccb114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PS Enterprise Games.'])[3]/preceding::span[6]</value>
      <webElementGuid>3e02a2cc-2eff-445f-bf9b-e02946c46d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div/div/span/span</value>
      <webElementGuid>a072e173-89b7-4310-bcb5-6f0c1eec4773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Please activate your account' or . = 'Please activate your account')]</value>
      <webElementGuid>bf9361bf-a8e3-4a1c-8aeb-fff67d5ea2d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
