<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-PS Enterprise Gameshop Hello from PS _9ac359</name>
   <tag></tag>
   <elementGuidId>d51cdcea-a967-4b51-92cb-12868232a8e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id=':6k']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a1feeb51-0f96-415c-b3d6-ea2f6953604c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:6k</value>
      <webElementGuid>223db656-c86c-40cd-a6a4-ecc5ac8e13e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>y2</value>
      <webElementGuid>cad38c5b-7840-45c4-a1b3-5366f2aec9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> - PS Enterprise Gameshop Hello from PS Enterprise Gameshop! Welcome to PS Enterprise Gameshop Thanks for creating an account on PS Enterprise Gameshop. Your username is ads.sto13 You can access your</value>
      <webElementGuid>1449a54b-3489-45ab-a46b-42cf694ea24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:6k&quot;)</value>
      <webElementGuid>4cf2b135-37d2-47c6-9370-0d07d759f099</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id=':6k']</value>
      <webElementGuid>118a2d9b-8b34-4c28-bce3-5a7ffe964ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id=':6h']/div/div/span</value>
      <webElementGuid>685c56d4-3300-4ad6-b6eb-f23839e1bd3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your PS Enterprise Gameshop account has been created!'])[2]/following::span[1]</value>
      <webElementGuid>8db7607d-3f19-416a-8188-9ceea69e2c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PS Enterprise Games.'])[2]/following::span[3]</value>
      <webElementGuid>3e98847c-eeb7-4968-9bcd-888c4a976441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Google Account .'])[1]/preceding::span[5]</value>
      <webElementGuid>94576ac1-f665-40b8-b04a-cac7dc737257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PS Enterprise Gameshop Hello from PS Enterprise Gameshop! Welcome to PS Enterprise Gameshop Thanks for creating an account on PS Enterprise Gameshop. Your username is ads.sto13 You can access your']/parent::*</value>
      <webElementGuid>3124b377-62d5-4990-8af0-481b29b5efce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div/span</value>
      <webElementGuid>d78bbd97-b8b8-41bb-9ba3-b77df1a4363c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = ':6k' and (text() = ' - PS Enterprise Gameshop Hello from PS Enterprise Gameshop! Welcome to PS Enterprise Gameshop Thanks for creating an account on PS Enterprise Gameshop. Your username is ads.sto13 You can access your' or . = ' - PS Enterprise Gameshop Hello from PS Enterprise Gameshop! Welcome to PS Enterprise Gameshop Thanks for creating an account on PS Enterprise Gameshop. Your username is ads.sto13 You can access your')]</value>
      <webElementGuid>d4d67bd6-4b2b-4f34-bab8-5a944c2dd489</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
